# Generated by Django 3.0 on 2019-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_problems', '0002_auto_20191206_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='equipamento_tipo',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tarifario',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='devices',
            field=models.ManyToManyField(to='technical_problems.Equipamento_Tipo'),
        ),
        migrations.AddField(
            model_name='client',
            name='tariffs',
            field=models.ManyToManyField(to='technical_problems.Tarifario'),
        ),
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(to='technical_problems.ServiceType'),
        ),
    ]
