# Generated by Django 3.0.1 on 2019-12-22 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento_Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(choices=[('tv', 'TV'), ('internet', 'Internet'), ('voz', 'Voz')], default='tv', max_length=8)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='technical_problems.Equipamento_Tipo')),
                ('tarifario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='technical_problems.Tarifario')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('morada', models.CharField(default='', max_length=256, primary_key=True, serialize=False)),
                ('servicos', models.ManyToManyField(to='technical_problems.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_problems.Contrato')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
