# Generated by Django 3.0 on 2019-12-17 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technical_problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('morada', models.CharField(default='', max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipamento_tipo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipamento_tipo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tarifario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tarifario',
            name='name',
        ),
        migrations.AddField(
            model_name='equipamento_tipo',
            name='nome',
            field=models.CharField(default='', max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='equipamento_tipo',
            name='servico',
            field=models.IntegerField(choices=[(1, 'TV'), (2, 'Internet'), (3, 'Voz')], default=1),
        ),
        migrations.AddField(
            model_name='tarifario',
            name='nome',
            field=models.CharField(default='', max_length=256, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.AddField(
            model_name='contrato',
            name='equipamentos',
            field=models.ManyToManyField(to='technical_problems.Equipamento_Tipo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tarifario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='technical_problems.Tarifario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technical_problems.Contrato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
